### ISSUE TITLE
Add support for multiple SubnetIDs for Subnets which exist in multiple networks

### ISSUE THREAD

**Issue by joshua-kim** [ava-labs/apm#1]
Some networks might have multiple corresponding subnetIds. For example, I might have a network `foo` that I want to be able to install + join. It might have subnetID `1234` for testnet, but `5678` for mainnet, but both use the same `foovm`. We might want subnet definitions to look something like this:

```
alias: foo
networks: 
 testnet:
  subnetID: 1234
 mainnet:
  subnetID: 5678
vms:
 - foovm
...
```

... and users could join a subnet like so:
```
apm join-subnet --subnet-alias=foo --network=mainnet
```

This will only be needed once dynamic-whitelisting is enabled, at which point we can start using those APIs to correctly whitelist the right subnet id.
